extends:
  - airbnb
  - plugin:react/recommended
plugins:
  - react
  - jsx-a11y
  - import
env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  max-len: off
  no-case-declarations: off
  import/no-extraneous-dependencies: off
  react/prefer-stateless-function: off
  react/jsx-filename-extension: off
  react/display-name: off
  react/prop-types: off
  react/destructuring-assignment: off
  react/jsx-one-expression-per-line: off
  jsx-a11y/heading-has-content: off
  no-param-reassign: off
