language: node_js

services:
  - docker

cache: yarn

env:
  global:
    - PUBLIC_URL=/admin

matrix:
  include:
    - node_js: '9'
      env:
        - DEPLOY=1
    - node_js: '10'

before_install:
  - npm install yarn -g
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn run lint
  - yarn run build

after_script: greenkeeper-lockfile-upload

addons:
  ssh_known_hosts: s11.mydevil.net

before_deploy:
  - >-
    export APP_VERSION=$(cat package.json | grep "\"version\":" | sed -E
    "s/\s+\"version\": \"(.*)\",/v\1/") && echo $APP_VERSION
  - >-
    openssl aes-256-cbc -K $encrypted_48044a6e4342_key -iv
    $encrypted_48044a6e4342_iv -in ./deploy/mydevil_rsa.enc -out
    /tmp/mydevil_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/mydevil_rsa
  - ssh-add /tmp/mydevil_rsa
  - yarn global add conventional-changelog-cli

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/mydevil-deploy.sh
    on:
      branch: develop
      condition: $DEPLOY = 1
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/github-tag.sh
    on:
      branch: master
      condition: $DEPLOY = 1
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/docker-app-push.sh
    on:
      tags: true
      condition: $DEPLOY = 1
