language: node_js

node_js:
  - '9'

services:
  - docker

cache: yarn

env:
  - PUBLIC_URL=https://knit-test-api.tk/admin-on-rest

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn run lint
  - yarn run build

after_script: greenkeeper-lockfile-upload

addons:
  ssh_known_hosts: s11.mydevil.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_48044a6e4342_key -iv $encrypted_48044a6e4342_iv -in ./deploy/mydevil_rsa.enc -out /tmp/mydevil_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/mydevil_rsa
  - ssh-add /tmp/mydevil_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/mydevil-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/docker-app-push.sh
    on:
      tags: true
